services:
  games.api:
    environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=3000
       # - ASPNETCORE_HTTPS_PORTS=3001
       # - ASPNETCORE_Kestrel__Certificates__Default__Password=123
       # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/games.pfx
    container_name: games.api
    image: games.api
    build:
      context: .
      dockerfile: Games.Presentation/Dockerfile
    ports:
        - "3000:3000"
        #- "3001:3001"
    #volumes:
        #- ~/.aspnet/https:/https:ro
    depends_on:
        database.server:
            condition: service_healthy
   

  database.server:
    container_name: database.server  
    image: "mcr.microsoft.com/mssql/server"  
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=SuperPassword123
    volumes:
        - ./sqlserver/data:/var/opt/mssql/data
        - ./sqlserver/log:/var/opt/mssql/log
    healthcheck:
        test: ["CMD-SHELL", "exit 0"]
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s

  games.client:
    container_name: games.client
    image: games.client
    build:
        context: Games.Presentation/Client/games
        dockerfile: Dockerfile
    ports:
        - "5000:5000"
    depends_on:
        - games.api

        
  
